### PR TITLE
Fix mismatch between Chisel and Firrtl on UInt -& UInt

### LINKED ISSUE #501: -& Returns UInt in Chisel, SInt in Firrtl
See issue in https://groups.google.com/forum/#!topic/chisel-users/KT_kN52yz14

I have a fix in the works

### PR DESCRIPTION
**Pull request by jackkoenig**
Fixes #501. Also added UIntOps test.

### CODE REVIEW

File: src/test/scala/chiselTests/UIntOps.scala [hunk 1]
```diff
@@ -5,18 +5,22 @@ package chiselTests
...
-    val modout = Output(UInt(16.W))
-    val lshiftout = Output(UInt(16.W))
-    val rshiftout = Output(UInt(16.W))
+    val a = Input(UInt(32.W))
+    val b = Input(UInt(32.W))
+    val addout = Output(UInt(32.W))
+    val subout = Output(UInt(32.W))
+    val addampout = Output(UInt(33.W))
+    val subampout = Output(UInt(33.W))
+    //val subampout = Output(UInt(32.W))
```
Comment (azidar) [inline src/test/scala/chiselTests/UIntOps.scala]: remove commented code

**Comment by jackkoenig** [comment]
I removed the comments (and removed the couple of extra lines that were working around #500 which was merged in the meantime)
